version: '2.3'
# TODO password passed during container build step?
services:
    db:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        networks:
            - frontend
            - backend
        expose:
            - 9200
            - 9300
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - es_data:/usr/share/elasticsearch/data
        healthcheck:
          test: ["CMD", "curl","-u", "localhost:9200"]
          interval: 30s
          timeout: 5s
          retries: 10
    kibana:
        image: docker.elastic.co/kibana/kibana:6.2.3
        networks:
            - frontend
        expose:
            - 5601
        ports:
            - 8080:5601
        volumes:
            - ./kibana/config/:/usr/share/kibana/config
        depends_on:
            db:
                condition: service_healthy
    dashboard:
        build:
            context: dashboard
        expose:
            - 8080
        ports:
            - 8042:8080
        networks:
            - frontend

networks:
    frontend:
    backend:
volumes:
    es_data:
