version: '2.3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        expose:
            - 2181
        environment:
            ZOOKEEPER_CLIENT_PORTY: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - kafka_net
    kafka:
        image: wurstmeister/kafka
        expose:
            - 9092
        environment:
            KAFKA_CREATE_TOPICS: "transaction_hist:1:1,transaction_str:1:1,miners_hist:1:1,miners_str:1:1,price_str:1:1"

            KAFKA_LOG_RETENTION_HOURS: 0
            KAFKA_LOG_RETENTION_MINUTES: 1

            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka/9092

            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 36000
            KAFKA_MESSAGE_MAX_BYTES: 10000000

            LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: WARN, authorizerAppender
        depends_on:
            - zookeeper
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - kafka_net
networks:
    kafka_net:
