version: '2.2'
# TODO SPLITME!
# TODO password passed during container build step?
services:
    app:
        build:
            context: app
            args:
                ELASTIC_PASSWORD: $ELASTIC_PASSWORD
        networks:
            - backend
        depends_on:
            db:
                condition: "service_healthy"
    db:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        networks:
            - frontend
            - backend
        expose:
            - 9200
            - 9300
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - es_data:/usr/share/elasticsearch/data
        healthcheck:
          test: ["CMD", "curl","-u","elastic:$ELASTIC_PASSWORD", "localhost:9200"]
          interval: 30s
          timeout: 5s
          retries: 10
    kibana:
        image: docker.elastic.co/kibana/kibana-x-pack:6.2.3
        networks:
            - frontend
        expose:
            - 5061
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        depends_on:
            db:
                condition: service_healthy
    kafka:
        environment:
            # TODO !!
            KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
            HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        image: wurstmeister/kafka # NOTE switch to spotify/kafka if fail
        networks:
            - zookeeper_network
            - backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    zookeeper:
        image: zookeeper:3.4.10
        networks:
            - zookeeper_network
    nginx:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - frontend
        ports:
            - 1234:80
networks:
    frontend:
    backend:
    zookeeper_network:
volumes:
    es_data:
