---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.username: elastic
xpack.monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.url: http://db:9200
elasticsearch.password: TcsMxpW1Cf7q9pGiThsg
